- name: Install Postgres dependencies
  apt: name={{item}}
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
    - python-pip
- pip: name=psycopg2

- name: Allow vagrant to sudo as postgres
  lineinfile:
    dest: /etc/sudoers
    line: vagrant ALL=(postgres) ALL
    validate: 'visudo -cf %s'

- name: Create Helloworld user
  postgresql_user: name=helloworld password=helloworld role_attr_flags=CREATEDB,SUPERUSER
  sudo_user: postgres

- name: Create Critiqual user
  postgresql_user: name=critiqual password=critiqual role_attr_flags=CREATEDB,SUPERUSER
  sudo_user: postgres